### PR TITLE
AMD and CommonJs support

### PR DESCRIPTION
**Pull request by duzun**
This is a great library, but it doesn't conform neither to AMD, nor to CommonJs.

As a polyfill it has to change the global scope to conform to the specs, but this is not always possible or desired.
For example, in Firefox Addon there is no way of changing the global (it is a Sandbox), thus there is no way this library can be included (`require('.setImmediate')` doesn't work, even though it is CommonJs environment). 
There might be other environments that prohibit changing the global scope in any way.

On the other hand, even when possible, it might be undesirable to change the global scope and this is what AMD is all about. I should be able to load two different implementations of `setImmediate()` at the same time without any conflict.

The changes I made:
1. When loaded using AMD, no global scope touched, but export `toGlobal()` method, so that user can choose to export `setImmadiate` to global scope.
2. When in CommonJs nevironment, add `setImmediate` and `clearImmediate` to `exports`. Because I didn't wanna change old behaviour, in CommonJs it still tries to export to global as well, but I would not do that unless desired (eg. use `toGlobal`).

### CODE REVIEW

**Comment by domenic** [comment]
Dupe of #38.

**Comment by duzun** [comment]
Not 100% dupe!
I have nothing against shims, but I just have no way to use it in Firefox Addon! 
In addition to trying to patch the global (yes, trying!), it should also export something.

**Comment by domenic** [comment]
Sorry, you should probably create another package for that. That's not the purpose of this package.

**Comment by duzun** [comment]
Ok, got it.
Thanks

**Pull request closed without merging**
