### PR TITLE
Replacing the <script> solution by an Image() solution

### PR DESCRIPTION
**Pull request by Lcfvs**
Create an `` element; its load/error event will be fired asynchronously.

This solution is an non-intrusive alternative to the `<script>` solution, because it doesn't need to be embedded to the document.

Enjoy ;)

### CODE REVIEW

**Comment by domenic** [comment]
Why is this better?

**Comment by Lcfvs** [comment]
Because it doesn't change the DOM, nor fire the related events (Mutations & Co)

**Comment by domenic** [comment]
OK. But have you actually tested this in IE6? IE6 doesn't support data URLs, so I am very skeptical. And, are you sure this is faster than setTimeout(,0) there?

In general, making a change of this magnitude to the older-browser support path is going to require a lot of evidence. I'd accept something like sauce labs jobs on IE6, 7, and 8 showing that the tests all pass, with the addition of another test showing that this occurs before setTimeout(,0). Screenshots would also work if sauce labs is not your thing. But without such evidence, it's not a good idea to disturb this code.

**Comment by Lcfvs** [comment]
Perfs aren't tested but for the IE6 support, it's why I cheat with `image.onerror = image.onload = ...`.

If the data URLs are supported, it fires the "load" event... else, the "error" event. :)

**Comment by domenic** [comment]
OK. Well, let me know when you have some stronger proof (screenshots or test runs or whatever) that this change does actually work in IE6 through 8.

**Comment by Lcfvs** [comment]
I sent a simplified version, even if the base64 solution works...

And I made the required tests : https://github.com/Lcfvs/setImmediate/blob/gh-pages/saucelabs-snapshot-ie.md

Imho, this cheat must be retro-compatible with the DOM-0, then Netscape 2.0

**Comment by duzun** [comment]
Are you serious about IE6? 
Is there anyone still using IE6?
Is it even possible to navigate the web with IE6?

**Comment by domenic** [comment]
@Lcfvs I am so sorry that I did not see your message back on July 31. I merged this as e5f53eb39cb1404aa8051f9b90170a9ef684d851.

**Comment by mbest** [comment]
I just tested this in IE8 and the `onerror` event is not async.

**Comment by domenic** [comment]
@mbest thanks, reverted and released 1.0.4.

**Pull request closed without merging**
